# DATA PREPROCESSING/DATA PREPARATION

## 1. Import Necessary Libraries

In [2]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

## 2. Import Dataset

In [3]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 3. Data Understanding

In [4]:
weather_data.shape

(158, 10)

In [5]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [6]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [7]:
weather_data.describe(include = "all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [8]:
weather_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [9]:
weather_data["Weather"].value_counts(dropna = False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

## 4. Data Preparation

#### Stage 1. Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype

In [10]:
weather_data.drop(labels = ["Unnamed: 0","Temp C"], axis = 1, inplace =  True)

In [11]:
weather_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [12]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [13]:
weather_data.shape

(158, 8)

In [14]:
38/158 #no.of null enteries divided by total no.of data

0.24050632911392406

In [15]:
del weather_data["Ozone"] # im dropping this "Ozone" column as 25% of the data is NaN

In [16]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [17]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [18]:
weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [19]:
weather_data["Solar.R"] = weather_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [20]:
weather_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [21]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [22]:
weather_data.dropna(inplace = True)

In [23]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [24]:
weather_data.shape

(155, 7)

In [25]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [26]:
weather_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [27]:
weather_data["Month"].replace(to_replace="May", value= 5 , inplace = True )

In [28]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [29]:
weather_data["Month"] = weather_data["Month"].astype("int")

In [30]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

## Stage 2 

### 2. Data Transformation
    * If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
    * If data is DISCRETE   = Label Encoder, One hot Encoder

In [31]:
weather_data

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [32]:
weather_data_copy_01 = weather_data.copy()
weather_data_copy_01

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

#### LabelEncoder

In [33]:
from sklearn.preprocessing import LabelEncoder

le_encoder = LabelEncoder()
weather_data_copy_01["Weather"] = le_encoder.fit_transform(weather_data_copy_01["Weather"])

In [34]:
weather_data_copy_01

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [35]:
weather_data_copy_01.dtypes

Solar.R    float64
Wind       float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather      int32
dtype: object

### 2. One Hot Encoder

This can be achieved by using any of the following 2 libraries:

1. Pandas - pd.get_dummies()
2. sklearn - OneHotEncoder()

In [36]:
weather_data_copy_02 = weather_data.copy()
weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [37]:
weather_data_copy_02 = pd.get_dummies(data=weather_data_copy_02,columns=["Weather"],dtype="int",drop_first=True)
weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67           0          1
1      118.0   8.0      5    2  2010    72           0          0
2      149.0  12.6      5    3  2010    74           1          0
3      313.0  11.5      5    4  2010    62           0          1
4      193.0  14.3      5    5  2010    56           0          1
..       ...   ...    ...  ...   ...   ...         ...        ...
153    190.0   7.4      5    1  2010    67           0          0
154    193.0   6.9      9   26  2010    70           1          0
155    145.0  13.2      9   27  2010    77           0          1
156    191.0  14.3      9   28  2010    75           0          1
157    131.0   8.0      9   29  2010    76           0          0

[155 rows x 8 columns]

In [38]:
weather_data_copy_02.dtypes

Solar.R       float64
Wind          float64
Month           int32
Day             int64
Year            int64
Temp            int64
Weather_PS      int32
Weather_S       int32
dtype: object

In [47]:
weather_data_copy_03 = weather_data.copy()
weather_data_copy_03

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [43]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
weather_data_copy_03 = ohe.fit_transform(weather_data_copy_03[["Weather"]])
weather_data_copy_03

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 155 stored elements and shape (155, 3)>

In [48]:
weather_data_copy_03 = pd.DataFrame(
    ohe.fit_transform(weather_data_copy_03[["Weather"]]).toarray(),
    columns=ohe.get_feature_names_out(["Weather"])
)

weather_data_copy_03

     Weather_C  Weather_PS  Weather_S
0          0.0         0.0        1.0
1          1.0         0.0        0.0
2          0.0         1.0        0.0
3          0.0         0.0        1.0
4          0.0         0.0        1.0
..         ...         ...        ...
150        1.0         0.0        0.0
151        0.0         1.0        0.0
152        0.0         0.0        1.0
153        0.0         0.0        1.0
154        1.0         0.0        0.0

[155 rows x 3 columns]